apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pgdb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: racedb
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
          image: postgres:14.5
          name: pgdb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: pgdb-claim0
      restartPolicy: Always
      volumes:
        - name: pgdb-claim0
          persistentVolumeClaim:
            claimName: pgdb-claim0
status: {}
