apiVersion: batch/v1
kind: CronJob
metadata:
  name: your-race-warm-up
  annotations:
      kompose.cmd: kompose convert -f docker-compose.yml
      kompose.version: 1.26.1 (a9d05d509)
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
  labels:
    app: your-race
    io.kompose.service: your-race         
spec:
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
# │ │ │ │ │
# * * * * *
  schedule: "38 11 19 11 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: JDBC_DATABASE_PASSWORD
                  value: admin
                - name: JDBC_DATABASE_URL
                  value: jdbc:postgresql://pgdb:5432/racedb
                - name: JDBC_DATABASE_USERNAME
                  value: admin
                - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
                  value: rabbitmq:5672
                - name: RABBIT_URL
                  value: rabbitmq:5672
                - name: SPRING_RABBITMQ_HOST
                  value: rabbitmq
                - name: SPRING_RABBITMQ_PORT
                  value: "5672"
                - name: TOGGLZ_FEATURES_USECB_ENABLED
                  value: "false"
                - name: TOGGLZ_FEATURES_RABBITPRODUCER_ENABLED
                  value: "false"
              image: raquetelio/your-race:v20221118 #rafarex70/your-race:1.3.0-rc.2
              name: your-race
              ports:
                - name: web
                  containerPort: 8080
              resources:
                limits:
                  cpu: 1000m
                  memory: 1024Mi
                requests:
                  cpu: 700m
                  memory: 768Mi
          restartPolicy: OnFailure
