apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: your-race
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: your-race
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60



