apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: your-race
  name: your-race
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    io.kompose.service: your-race
status:
  loadBalancer: {}

