apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    app: your-race
    io.kompose.service: your-race
  name: your-race
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: your-race
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      creationTimestamp: null
      labels:
        app: your-race
        io.kompose.service: your-race
    spec:
      containers:
        - env:
            - name: JDBC_DATABASE_PASSWORD
              value: admin
            - name: JDBC_DATABASE_URL
              value: jdbc:postgresql://pgdb:5432/racedb
            - name: JDBC_DATABASE_USERNAME
              value: admin
            - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
              value: rabbitmq:5672
            - name: RABBIT_URL
              value: rabbitmq:5672
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: TOGGLZ_FEATURES_RABBITPRODUCER_ENABLED
              value: "true" 
          image: raquetelio/your-race:v1.3.1
          name: your-race
          ports:
            - name: web
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 700m
              memory: 768Mi
      restartPolicy: Always
status: {}
