openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://192.168.49.2
  description: Generated server url
paths:
  /api/tracks/{id}:
    get:
      tags:
      - track-resource
      operationId: getTrack
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDTO'
    put:
      tags:
      - track-resource
      operationId: updateTrack
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackDTO'
        required: true
      responses:
        "200":
          description: OK
    delete:
      tags:
      - track-resource
      operationId: deleteTrack
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /api/races/{id}:
    get:
      tags:
      - race-resource
      operationId: getRace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDTO'
    put:
      tags:
      - race-resource
      operationId: updateRace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaceDTO'
        required: true
      responses:
        "200":
          description: OK
    delete:
      tags:
      - race-resource
      operationId: deleteRace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /api/organizers/{id}:
    get:
      tags:
      - organizer-resource
      operationId: getOrganizer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizerDTO'
    put:
      tags:
      - organizer-resource
      operationId: updateOrganizer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizerDTO'
        required: true
      responses:
        "200":
          description: OK
    delete:
      tags:
      - organizer-resource
      operationId: deleteOrganizer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /api/athletes/{id}:
    get:
      tags:
      - athlete-resource
      operationId: getAthlete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AthleteDTO'
    put:
      tags:
      - athlete-resource
      operationId: updateAthlete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AthleteDTO'
        required: true
      responses:
        "200":
          description: OK
    delete:
      tags:
      - athlete-resource
      operationId: deleteAthlete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /api/tracks/byorder:
    post:
      tags:
      - track-resource
      operationId: createRegistrationByOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationByOrderDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDTO'
  /api/tracks/bydraw:
    post:
      tags:
      - track-resource
      operationId: createRegistrationByDraw
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationByDrawDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDTO'
  /api/races:
    get:
      tags:
      - race-resource
      operationId: getAllRaces
      parameters:
      - name: open
        in: query
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaceDTO'
    post:
      tags:
      - race-resource
      operationId: createRace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaceDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /api/organizers:
    get:
      tags:
      - organizer-resource
      operationId: getAllOrganizers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizerDTO'
    post:
      tags:
      - organizer-resource
      operationId: createOrganizer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizerDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /api/athletes:
    get:
      tags:
      - athlete-resource
      operationId: getAllAthletes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AthleteDTO'
    post:
      tags:
      - athlete-resource
      operationId: createAthlete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AthleteDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /api/applications:
    post:
      tags:
      - application-resource
      operationId: createApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequestDTO'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationDTO'
  /api/tracks:
    get:
      tags:
      - track-resource
      operationId: getTracks
      parameters:
      - name: open
        in: query
        required: true
        schema:
          type: boolean
      - name: trackDTO
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/TrackRequestDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackDTO'
  /api/applications/races/{id}:
    get:
      tags:
      - application-resource
      operationId: getRaceApplications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApplicationDTO'
  /api/applications/athletes/{id}:
    get:
      tags:
      - application-resource
      operationId: getAthleteApplicationRaces
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: open
        in: query
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApplicationDTO'
components:
  schemas:
    Score:
      type: object
      properties:
        time:
          type: number
        position:
          type: integer
          format: int32
    TrackDTO:
      required:
      - athleteId
      - raceId
      type: object
      properties:
        id:
          type: integer
          format: int64
        athleteId:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        raceId:
          type: integer
          format: int64
        raceName:
          type: string
        raceDate:
          type: string
          format: date-time
        registrationDate:
          type: string
          format: date-time
        paymentInfo:
          maxLength: 255
          minLength: 0
          type: string
        status:
          maxLength: 255
          minLength: 0
          type: string
        score:
          $ref: '#/components/schemas/Score'
        dorsal:
          type: integer
          format: int32
    RaceDTO:
      required:
      - location
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 255
          minLength: 0
          type: string
        description:
          maxLength: 1000
          minLength: 0
          type: string
        date:
          type: string
          format: date-time
        location:
          maxLength: 255
          minLength: 0
          type: string
        distance:
          type: number
          format: double
        type:
          maxLength: 255
          minLength: 0
          type: string
        athleteCapacity:
          type: integer
          format: int32
        availableCapacity:
          type: integer
          format: int32
        applicationInitialDate:
          type: string
          format: date-time
        applicationLastDate:
          type: string
          format: date-time
        organizerName:
          type: string
        raceRegistrationDate:
          type: string
          format: date-time
        registrationType:
          type: string
          enum:
          - BYDRAW
          - BYORDER
        registrationCost:
          type: number
          format: double
    OrganizerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 255
          minLength: 0
          type: string
    AthleteDTO:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 255
          minLength: 0
          type: string
        surname:
          maxLength: 255
          minLength: 0
          type: string
        trackRecord:
          $ref: '#/components/schemas/TrackRecord'
    TrackRecord:
      type: object
      properties:
        raceName:
          maxLength: 255
          minLength: 0
          type: string
        score:
          $ref: '#/components/schemas/Score'
        date:
          type: string
          format: date
    RegistrationByOrderDTO:
      required:
      - applicationCode
      type: object
      properties:
        applicationCode:
          maxLength: 10
          minLength: 0
          type: string
    RegistrationByDrawDTO:
      required:
      - athleteId
      - raceId
      type: object
      properties:
        athleteId:
          type: integer
          format: int64
        raceId:
          type: integer
          format: int64
    ApplicationRequestDTO:
      type: object
      properties:
        athleteId:
          type: integer
          format: int64
        raceId:
          type: integer
          format: int64
    ApplicationDTO:
      type: object
      properties:
        applicationCode:
          type: string
        name:
          type: string
        surname:
          type: string
        raceName:
          type: string
        date:
          type: string
          format: date-time
        raceRegistrationDate:
          type: string
          format: date-time
    TrackRequestDTO:
      type: object
      properties:
        athleteId:
          type: integer
          format: int64
        raceId:
          type: integer
          format: int64
