
name: PRMain

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: cd your-race
      - run: mvn test -Dtest=es.codeurjc.mastercloudapps.your_race.**
